# Generated by Django 3.2.16 on 2022-12-16 02:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='confir',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name1', models.CharField(max_length=250, unique=True)),
                ('Password', models.CharField(max_length=250, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='registration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name1', models.CharField(max_length=250, unique=True)),
                ('Password', models.CharField(max_length=250, unique=True)),
                ('cpassword', models.CharField(max_length=250, unique=True)),
            ],
        ),
    ]
